### ISSUE TITLE
自动关闭双重认证

### ISSUE THREAD

**Issue by itonky** [balala2oo8/AppleIDAuto#1]
这个功能根本不能用啊

**Comment by balala2oo8** [comment]
完全没有问题的

**Comment by balala2oo8** [comment]
> 这个功能根本不能用啊

完全没有问题的

**Comment by itonky** [comment]
> > 这个功能根本不能用啊
> 
> 完全没有问题的

搞定了，但是有一个功能不会用？

可以绝体解释一下吗 ？

api_host | api 地址

这个有啥用，能举个列子说一下吗，没摸过py  😂

**Comment by balala2oo8** [comment]
假设你的账号信息存储在你自己的网站中，你可以提供一个修改密码的接口，本程序会在修改密码成功后请求你的接口，以达到自动修改你网站中账号信息的目的。

**Comment by itonky** [comment]
> 假设你的账号信息存储在你自己的网站中，你可以提供一个修改密码的接口，本程序会在修改密码成功后请求你的接口，以达到自动修改你网站中账号信息的目的。

这个似懂非懂，以前用的PHP 只写过 get 和post 方法，如果目标的 api_host  是PHP 脚本语言 ，用 $_PUT 接收参数吗？ 用GET 或者POST 可以吗？

**Comment by itonky** [comment]
> 都可以

难道你的一直没问题，可以用正常用？？

我这里测试关掉双重认证没问题，但是解锁账号提示上面的错误！

**Comment by balala2oo8** [comment]
99%时间不会有错，够用即可
