### ISSUE TITLE
Message: 未找到 id 为 "password" 的元素

### ISSUE THREAD

**Issue by ivyshow** [balala2oo8/AppleIDAuto#13]
重置密码...
检查 i@icloud.com 时，超时了。Message: 未找到 id 为 "password" 的元素
Stacktrace:
#0 0x5610ad031c83 <unknown>
#1 0x5610acde5666 <unknown>
#2 0x5610ace1e518 <unknown>
#3 0x5610ace1e611 <unknown>
#4 0x5610ace5bee4 <unknown>
#5 0x5610ace4408d <unknown>
#6 0x5610ace59def <unknown>
#7 0x5610ace43f23 <unknown>
#8 0x5610ace12724 <unknown>
#9 0x5610ace13d68 <unknown>
#10 0x5610ad07059d <unknown>
#11 0x5610ad072247 <unknown>
#12 0x5610ad071c70 <unknown>
#13 0x5610ad072935 <unknown>
#14 0x5610ad05f27b <unknown>
#15 0x5610ad072c66 <unknown>
#16 0x5610ad0536ce <unknown>
#17 0x5610ad08ae95 <unknown>
#18 0x5610ad08b033 <unknown>
#19 0x5610ad0a47f0 <unknown>
#20 0x7f77a1f6fea7 start_thread

暂停10秒
正在检查  ...
Aplle ID() 信息有误！请检查！

**Comment by ivyshow** [comment]
Confirm your phone number.@hotmail.com)
正在关闭 @hotmail.com 的双重认证...
检查 @hotmail.com 时，超时了。Message: 元素 "last" 不可用

前两天测试还可以，请问是苹果又改了？

**Comment by balala2oo8** [comment]
没有更新，说明没有问题。

**Comment by ivyshow** [comment]
发现是虽然id是美区id，但是默认语言选择了中文导致的
