### ISSUE TITLE
启动的main.py出现报错

### ISSUE THREAD

**Issue by LatteCloud** [balala2oo8/AppleIDAuto#3]
UnicodeEncodeError: 'latin-1' codec can't encode characters in position 0-3: ordinal not in range(256)
![error](https://user-images.githubusercontent.com/101858171/182782462-3c1d10fe-c91b-4eea-a96a-e4f784c97d21.png)

**Comment by balala2oo8** [comment]
看起来似乎是 config.json 文件的问题
