### ISSUE TITLE
Message: css元素 "img" 不可用

### ISSUE THREAD

**Issue by seqilove** [balala2oo8/AppleIDAuto#4]
检查 xxxxxx@hotmail.com 时，超时了。Message: css元素 "img" 不可用

**Comment by seqilove** [comment]
搞了一天了,不知道问题出在哪里.希望作者能解答一下 谢谢.

**Comment by balala2oo8** [comment]
偶尔一次这是正常情况，因为是模拟浏览器操作，所以不可能100%没有问题。

**Comment by seqilove** [comment]
不是偶尔哦,一直都是这个提示

**Comment by balala2oo8** [comment]
出现这个问题是因为没有网页加载出验证码，从我自己使用的情况来看，大概几天才会出现一次。你可以换个vps试试

**Comment by seqilove** [comment]
好的,我再试试其他的 谢谢了.
